version: "3.6"

services:
  # PHP + Apache server
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./fm-diario:/var/www/html
      - ./docker/apache:/etc/apache2/sites-enabled
    ports:
      - 80:80
    restart: always
    environment:
      - TZ=America/Sao_Paulo
    networks:
      - difm

  # Mariadb server
  mariadb:
    image: mariadb:latest
    ports:
      - 3311:3306
    restart: always
    volumes:
      - ./docker/mariadb:/var/lib/mysql
    environment:
      - TZ=America/Sao_Paulo
      - MARIADB_ROOT_USER=root
      - MARIADB_ROOT_PASSWORD=root
      - MARIADB_DATABASE=difm
    networks:
      - difm

networks:
  difm:
