version: "3.6"

services:
  # PHP + Apache server
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/html
      - ./docker/apache:/etc/apache2/sites-enabled
    ports:
      - ${WEB_PORT}:80
    restart: always
    environment:
      - TZ=America/Sao_Paulo
    networks:
      - jrtoledo

  # Mariadb server
  mariadb:
    image: mariadb:latest
    ports:
      - 3311:3306
    restart: always
    volumes:
      - ./docker/mariadb:/var/lib/mysql
    environment:
      - TZ=America/Sao_Paulo
      - MARIADB_ROOT_USER=${DB_USERNAME}
      - MARIADB_ROOT_PASSWORD=${DB_PASSWORD}
      - MARIADB_DATABASE=${DB_DATABASE}
    networks:
      - jrtoledo

networks:
  jrtoledo:
    driver: bridge
